import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "./providers";
import { ThemeChanger } from "@/components/ThemeChanger";
import { getUser } from "@/lib/auth/auth.utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning className="dark">
      <body>
        <Providers user={await getUser()}>
          <ThemeChanger />
          <main className="max-w-5xl m-auto">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
