import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "./providers";
import { ThemeChanger } from "@/components/ThemeChanger";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning className="dark">
      <body>
        <Providers>
          <ThemeChanger />
          {children}
        </Providers>
      </body>
    </html>
  );
}
